# Autogenerated by Copilot to integrate GoogleWebRTC via CocoaPods
platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

project 'CrookedSentry.xcodeproj'

target 'CrookedSentry' do
  pod 'GoogleWebRTC'
end

post_install do |installer|
  # Disable Xcode 15 user script sandboxing which breaks rsync in CocoaPods scripts
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
  end
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |native_target|
      native_target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
